# Estimating At-Work Subtour Destination Choice

This notebook illustrates how to re-estimate a single model component for ActivitySim.  This process 
includes running ActivitySim in estimation mode to read household travel survey files and write out
the estimation data bundles used in this notebook.  To review how to do so, please visit the other
notebooks in this directory.

# Load libraries

In [1]:
import larch  # !conda install larch #for estimation
import pandas as pd
import numpy as np
import yaml 
import larch.util.excel
import os

We'll work in our `test` directory, where ActivitySim has saved the estimation data bundles.

In [2]:
os.chdir('test')

# Load data and prep model for estimation

In [3]:
modelname="atwork_subtour_destination"

In [4]:
from activitysim.estimation.larch import component_model
model, data = component_model(modelname, return_data=True)

# Review data loaded from EDB

Next we can review what was read the EDB, including the coefficients, model settings, utilities specification, and chooser and alternative data.

## coefficients

In [5]:
data.coefficients

                                                      value constrain
coefficient_name
coef_distance_piecewise_linear_from_0_to_1_miles    -0.7926         F
coef_distance_piecewise_linear_from_1_to_2_miles    -0.7926         F
coef_distance_piecewise_linear_from_2_to_5_miles    -0.5197         F
coef_distance_piecewise_linear_from_5_to_15_miles   -0.2045         F
coef_distance_piecewise_linear_for_15_plus_miles    -0.2045         F
coef_size_variable_atwork                            1.0000         T
coef_no_attractions_atwork_size_variable_is_0     -999.0000         T
coef_mode_choice_logsum                              0.5136         F
coef_sample_of_alternatives_correction_factor        1.0000         T

## alt_values

In [6]:
data.alt_values

,tour_id,variable,1,2,3,4,5,6,7,8,...,181,182,183,184,185,186,187,188,189,190
0,2998927,util_distance_piecewise_linear_for_15_plus_miles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2998927,util_distance_piecewise_linear_from_0_to_1_miles,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,2998927,util_distance_piecewise_linear_from_1_to_2_miles,1.0,0.9299999475479126,0.7599999904632568,0.7699999809265137,0.4700000286102295,0.2799999713897705,0.12000000476837158,0.25999999046325684,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,2998927,util_distance_piecewise_linear_from_2_to_5_miles,0.029999971389770508,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,3.0,3.0,2.9600000381469727,3.0,3.0,3.0,3.0,3.0
4,2998927,util_distance_piecewise_linear_from_5_to_15_miles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8899998664855957,1.8000001907348633,1.3299999237060547,0.48999977111816406,0.0,1.0799999237060547,0.9899997711181641,1.070000171661377,1.929999828338623,2.130000114440918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4171,308000674,util_distance_piecewise_linear_from_5_to_15_miles,1.4200000762939453,1.3600001335144043,1.2899999618530273,1.1700000762939453,0.9699997901916504,0.9699997901916504,0.809999942779541,0.6100001335144043,...,0.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4172,308000674,util_mode_choice_logsum,1.743683315365601,1.8090398438241646,1.9187317689932244,1.845763258455972,1.9118565509402088,2.070472775294134,2.0749647025662954,2.0765252832944836,...,1.4896400525368332,1.9120295717956781,1.9541420210552534,1.9566568956436885,2.1147517922008467,2.110613932849587,2.36614159716225,2.675175002962727,2.45867106695333,2.161156410360593
4173,308000674,util_no_attractions_atwork_size_variable_is_0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4174,308000674,util_sample_of_alternatives_correction_factor,5.621843324877587,4.892390701697378,6.41959006998515,5.121864578661301,4.0943304970661645,5.6640922965207166,4.849601771676099,5.493466028204648,...,7.195735435552638,6.66177523532048,5.775893570617849,5.627447629966182,5.316640911769303,5.484197717810032,5.248188568415137,3.3386531188982147,7.377276636224848,5.8249441461146
4175,308000674,util_size_variable_atwork,6.577240859271166,7.294423493874009,5.752909090156044,7.026094604325162,8.012728626482545,6.442966827027993,7.224737382332969,6.539973163879868,...,4.866333729879064,5.1845549872093715,5.945708525269778,6.047381635266343,6.06715626447492,5.987948372605412,5.730242629913322,7.343549119396827,3.6375335267623483,5.304200029706192

## chooser_data

In [7]:
data.chooser_data

,tour_id,model_choice,override_choice,person_id,workplace_zone_id,income_segment
0,2998927,114,115.0,73144,77,1
1,3060326,83,83.0,74642,165,1
2,4422879,164,164.0,107875,161,1
3,4440282,75,76.0,108299,112,1
4,4496780,34,27.0,109677,181,1
...,...,...,...,...,...,...
459,302923726,71,71.0,7388383,36,4
460,302942567,87,87.0,7388843,42,4
461,302942627,67,67.0,7388844,17,4
462,305120465,130,130.0,7441962,127,4
463,308000674,17,16.0,7512211,162,1

## landuse

In [8]:
data.landuse

,DISTRICT,SD,county_id,TOTHH,TOTPOP,TOTACRE,RESACRE,CIACRE,TOTEMP,AGE0519,...,area_type,HSENROLL,COLLFTE,COLLPTE,TOPOLOGY,TERMINAL,household_density,employment_density,density_index,is_cbd
zone_id,,,,,,,,,,,,,,,,,,,,,
1,1,1,1,46,82,20.3,1.0,15.00000,27318,7,...,0,0.00000,0.00000,0.00000,3,5.89564,2.875000,1707.375000,2.870167,False
2,1,1,1,134,240,31.1,1.0,24.79297,42078,19,...,0,0.00000,0.00000,0.00000,1,5.84871,5.195214,1631.374751,5.178722,False
3,1,1,1,267,476,14.7,1.0,2.31799,2445,38,...,0,0.00000,0.00000,0.00000,1,5.53231,80.470405,736.891913,72.547987,False
4,1,1,1,151,253,19.3,1.0,18.00000,22434,20,...,0,0.00000,0.00000,0.00000,2,5.64330,7.947368,1180.736842,7.894233,False
5,1,1,1,611,1069,52.7,1.0,15.00000,15662,86,...,0,0.00000,72.14684,0.00000,1,5.52555,38.187500,978.875000,36.753679,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,4,4,1,2779,8062,376.0,172.0,15.00000,1760,1178,...,3,0.00000,0.00000,0.00000,1,2.04173,14.860963,9.411765,5.762347,False
187,4,4,1,1492,4139,214.0,116.0,10.00000,808,603,...,3,0.00000,0.00000,0.00000,2,1.73676,11.841270,6.412698,4.159890,False
188,4,4,1,753,4072,232.0,11.0,178.00000,4502,1117,...,2,3961.04761,17397.79102,11152.93652,1,2.28992,3.984127,23.820106,3.413233,False
189,4,4,1,3546,8476,201.0,72.0,6.00000,226,1057,...,2,0.00000,0.00000,0.00000,1,2.88773,45.461538,2.897436,2.723836,False
190,4,4,1,968,1647,1381.0,14.0,28.00000,1010,114,...,3,0.00000,0.00000,0.00000,1,2.60309,23.047619,24.047619,11.768501,False

## spec

In [9]:
data.spec

,Label,Description,Expression,atwork
0,util_distance_piecewise_linear_from_0_to_1_miles,"Distance, piecewise linear from 0 to 1 miles","@skims['DIST'].clip(0,1)",coef_distance_piecewise_linear_from_0_to_1_miles
1,util_distance_piecewise_linear_from_1_to_2_miles,"Distance, piecewise linear from 1 to 2 miles","@(skims['DIST']-1).clip(0,1)",coef_distance_piecewise_linear_from_1_to_2_miles
2,util_distance_piecewise_linear_from_2_to_5_miles,"Distance, piecewise linear from 2 to 5 miles","@(skims['DIST']-2).clip(0,3)",coef_distance_piecewise_linear_from_2_to_5_miles
3,util_distance_piecewise_linear_from_5_to_15_miles,"Distance, piecewise linear from 5 to 15 miles","@(skims['DIST']-5).clip(0,10)",coef_distance_piecewise_linear_from_5_to_15_miles
4,util_distance_piecewise_linear_for_15_plus_miles,"Distance, piecewise linear for 15+ miles",@(skims['DIST']-15.0).clip(0),coef_distance_piecewise_linear_for_15_plus_miles
5,util_no_attractions_atwork_size_variable_is_0,"No attractions, atwork size_term variable is 0",size_term==0,coef_no_attractions_atwork_size_variable_is_0
6,util_mode_choice_logsum,Mode choice logsum,mode_choice_logsum,coef_mode_choice_logsum
7,util_sample_of_alternatives_correction_factor,Sample of alternatives correction factor,"@np.minimum(np.log(df.pick_count/df.prob), 60)",coef_sample_of_alternatives_correction_factor

## size_spec

In [10]:
data.size_spec

         RETEMPN  HEREMPN
segment
atwork     0.742    0.258

# Estimate

With the model setup for estimation, the next step is to estimate the model coefficients.  Make sure to use a sufficiently large enough household sample and set of zones to avoid an over-specified model, which does not have a numerically stable likelihood maximizing solution.  Larch has a built-in estimation methods including BHHH, and also offers access to more advanced general purpose non-linear optimizers in the `scipy` package, including SLSQP, which allows for bounds and constraints on parameters.  BHHH is the default and typically runs faster, but does not follow constraints on parameters.

In [11]:
model.estimate(method='BHHH', options={'maxiter':1000})

req_data does not request avail_ca or avail_co but it is set and being provided
converting data_ca to <class 'numpy.float64'>

,value,initvalue,nullvalue,minimum,maximum,holdfast,note,best
atwork_HEREMPN,-1.707324,-1.354796,0.0,-6.0,6.0,0,,-1.707324
atwork_RETEMPN,-0.298406,-0.298406,0.0,-6.0,6.0,1,,-0.298406
coef_distance_piecewise_linear_for_15_plus_miles,-0.204500,-0.204500,0.0,NaN,NaN,0,,-0.204500
coef_distance_piecewise_linear_from_0_to_1_miles,-1.364154,-0.792600,0.0,NaN,NaN,0,,-1.364154
coef_distance_piecewise_linear_from_1_to_2_miles,-0.739532,-0.792600,0.0,NaN,NaN,0,,-0.739532
coef_distance_piecewise_linear_from_2_to_5_miles,-0.504526,-0.519700,0.0,NaN,NaN,0,,-0.504526
coef_distance_piecewise_linear_from_5_to_15_miles,-0.073403,-0.204500,0.0,NaN,NaN,0,,-0.073403
coef_mode_choice_logsum,0.503271,0.513600,0.0,NaN,NaN,0,,0.503271
coef_no_attractions_atwork_size_variable_is_0,-999.000000,-999.000000,0.0,NaN,NaN,1,,-999.000000
coef_sample_of_alternatives_correction_factor,1.000000,1.000000,0.0,NaN,NaN,1,,1.000000

/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 5.1460637824515034e-14 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 3.192541283407413e-14 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 3.498478984793179e-14 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 1.0731153205050762e-13 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 1.333452476333678e-13 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 1.7862187878568713e-14 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 5.750088707308852e-14 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 1.0701560851092294e-14 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 1.0186281177938627e-13 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")
/Users/jeffnewman/OneDrive - Cambridge Systematics/Git/larch/larch/linalg/__init__.py:18: UserWarning: minimum eig 1.0837304994953431e-13 in general_inverse
  warnings.warn(f"minimum eig {min_eig} in general_inverse")

┣          loglike: -2329.8700459477177
┣                x: atwork_HEREMPN                                        -1.707324
┃                   atwork_RETEMPN                                        -0.298406
┃                   coef_distance_piecewise_linear_for_15_plus_miles      -0.204500
┃                   coef_distance_piecewise_linear_from_0_to_1_miles      -1.364154
┃                   coef_distance_piecewise_linear_from_1_to_2_miles      -0.739532
┃                   coef_distance_piecewise_linear_from_2_to_5_miles      -0.504526
┃                   coef_distance_piecewise_linear_from_5_to_15_miles     -0.073403
┃                   coef_mode_choice_logsum                                0.503271
┃                   coef_no_attractions_atwork_size_variable_is_0       -999.000000
┃                   coef_sample_of_alternatives_correction_factor          1.000000
┃                   dtype: float64
┣        tolerance: 8.076677745948512e-06
┣            steps: array([1., 1., 1., 1., 1., 1., 1., 1.])
┣          message: 'Optimization terminated successfully.'
┣     elapsed_time: datetime.timedelta(microseconds=121814)
┣           method: 'BHHH'
┣          n_cases: 464
┣ iteration_number: 8
┣          logloss: 5.021271650749392

### Estimated coefficients

In [12]:
model.parameter_summary()

# Output Estimation Results

In [13]:
from activitysim.estimation.larch import update_coefficients, update_size_spec
result_dir = data.edb_directory/"estimated"

## Write updated utility coefficients

In [14]:
update_coefficients(
    model, data, result_dir,
    output_file=f"{modelname}_coefficients_revised.csv",
);

## Write updated size coefficients

In [15]:
update_size_spec(
    model, data, result_dir, 
    output_file=f"{modelname}_size_terms.csv",
)

,segment,model_selector,TOTHH,RETEMPN,FPSEMPN,HEREMPN,OTHEMPN,AGREMPN,MWTEMPN,AGE0519,HSENROLL,COLLFTE,COLLPTE
0,work_low,workplace,0.000000,0.129129,0.193193,0.383383,0.120120,0.010010,0.164164,0.000,0.000000,0.000000,0.000000
1,work_med,workplace,0.000000,0.120120,0.197197,0.325325,0.139139,0.008008,0.210210,0.000,0.000000,0.000000,0.000000
2,work_high,workplace,0.000000,0.110000,0.207000,0.284000,0.154000,0.006000,0.239000,0.000,0.000000,0.000000,0.000000
3,work_veryhigh,workplace,0.000000,0.093000,0.270000,0.241000,0.146000,0.004000,0.246000,0.000,0.000000,0.000000,0.000000
4,university,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.592000,0.408000
5,gradeschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000,0.000000,0.000000,0.000000
6,highschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.000000,0.000000,0.000000
7,escort,non_mandatory,0.000000,0.225000,0.000000,0.144000,0.000000,0.000000,0.000000,0.465,0.166000,0.000000,0.000000
8,shopping,non_mandatory,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
9,eatout,non_mandatory,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
10,othmaint,non_mandatory,0.000000,0.482000,0.000000,0.518000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
11,social,non_mandatory,0.000000,0.522000,0.000000,0.478000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
12,othdiscr,non_mandatory,0.252252,0.212212,0.000000,0.272272,0.165165,0.000000,0.000000,0.000,0.098098,0.000000,0.000000
13,atwork,atwork,0.000000,0.803595,0.000000,0.196405,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
14,work,trip,0.000000,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.000,0.000000,0.000000,0.000000
15,escort,trip,0.001000,0.225000,0.000000,0.144000,0.000000,0.000000,0.000000,0.464,0.166000,0.000000,0.000000
16,shopping,trip,0.001000,0.999000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
17,eatout,trip,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
18,othmaint,trip,0.001000,0.481000,0.000000,0.518000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
19,social,trip,0.001000,0.521000,0.000000,0.478000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
20,othdiscr,trip,0.252252,0.212212,0.000000,0.272272,0.165165,0.000000,0.000000,0.000,0.098098,0.000000,0.000000
21,univ,trip,0.000999,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.591409,0.407592

## Write the model estimation report, including coefficient t-statistic and log likelihood

In [16]:
model.to_xlsx(
    result_dir/f"{modelname}_model_estimation.xlsx", 
    data_statistics=False,
);

# Next Steps

The final step is to either manually or automatically copy the `*_coefficients_revised.csv` file and `*_size_terms.csv` file to the configs folder, rename them to `*_coefficients.csv` and `destination_choice_size_terms.csv`, and run ActivitySim in simulation mode.  Note that all the location
and desintation choice models share the same `destination_choice_size_terms.csv` input file, so if you
are updating all these models, you'll need to ensure that updated sections of this file for each model
are joined together correctly.

In [17]:
pd.read_csv(result_dir/f"{modelname}_coefficients_revised.csv")

                                    coefficient_name       value constrain
0   coef_distance_piecewise_linear_from_0_to_1_miles   -1.364154         F
1   coef_distance_piecewise_linear_from_1_to_2_miles   -0.739532         F
2   coef_distance_piecewise_linear_from_2_to_5_miles   -0.504526         F
3  coef_distance_piecewise_linear_from_5_to_15_miles   -0.073403         F
4   coef_distance_piecewise_linear_for_15_plus_miles   -0.204500         F
5                          coef_size_variable_atwork    1.000000         T
6      coef_no_attractions_atwork_size_variable_is_0 -999.000000         T
7                            coef_mode_choice_logsum    0.503271         F
8      coef_sample_of_alternatives_correction_factor    1.000000         T

In [18]:
pd.read_csv(result_dir/f"{modelname}_size_terms.csv")

,index,segment,model_selector,TOTHH,RETEMPN,FPSEMPN,HEREMPN,OTHEMPN,AGREMPN,MWTEMPN,AGE0519,HSENROLL,COLLFTE,COLLPTE
0,0,work_low,workplace,0.000000,0.129129,0.193193,0.383383,0.120120,0.010010,0.164164,0.000,0.000000,0.000000,0.000000
1,1,work_med,workplace,0.000000,0.120120,0.197197,0.325325,0.139139,0.008008,0.210210,0.000,0.000000,0.000000,0.000000
2,2,work_high,workplace,0.000000,0.110000,0.207000,0.284000,0.154000,0.006000,0.239000,0.000,0.000000,0.000000,0.000000
3,3,work_veryhigh,workplace,0.000000,0.093000,0.270000,0.241000,0.146000,0.004000,0.246000,0.000,0.000000,0.000000,0.000000
4,4,university,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.592000,0.408000
5,5,gradeschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000,0.000000,0.000000,0.000000
6,6,highschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.000000,0.000000,0.000000
7,7,escort,non_mandatory,0.000000,0.225000,0.000000,0.144000,0.000000,0.000000,0.000000,0.465,0.166000,0.000000,0.000000
8,8,shopping,non_mandatory,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
9,9,eatout,non_mandatory,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
10,10,othmaint,non_mandatory,0.000000,0.482000,0.000000,0.518000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
11,11,social,non_mandatory,0.000000,0.522000,0.000000,0.478000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
12,12,othdiscr,non_mandatory,0.252252,0.212212,0.000000,0.272272,0.165165,0.000000,0.000000,0.000,0.098098,0.000000,0.000000
13,13,atwork,atwork,0.000000,0.803595,0.000000,0.196405,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
14,14,work,trip,0.000000,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.000,0.000000,0.000000,0.000000
15,15,escort,trip,0.001000,0.225000,0.000000,0.144000,0.000000,0.000000,0.000000,0.464,0.166000,0.000000,0.000000
16,16,shopping,trip,0.001000,0.999000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
17,17,eatout,trip,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
18,18,othmaint,trip,0.001000,0.481000,0.000000,0.518000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
19,19,social,trip,0.001000,0.521000,0.000000,0.478000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
20,20,othdiscr,trip,0.252252,0.212212,0.000000,0.272272,0.165165,0.000000,0.000000,0.000,0.098098,0.000000,0.000000
21,21,univ,trip,0.000999,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.591409,0.407592