# Estimating Trip Destination Choice

This notebook illustrates how to re-estimate a single model component for ActivitySim.  This process 
includes running ActivitySim in estimation mode to read household travel survey files and write out
the estimation data bundles used in this notebook.  To review how to do so, please visit the other
notebooks in this directory.

# Load libraries

In [1]:
import larch as lx
import pandas as pd

lx.versions()

JAX not found. Some functionality will be unavailable.

{'larch': '6.0.32',
 'sharrow': '2.13.0',
 'numpy': '1.26.4',
 'pandas': '1.5.3',
 'xarray': '2024.3.0',
 'numba': '0.60.0'}

For this demo, we will assume that you have already run ActivitySim in estimation
mode, and saved the required estimation data bundles (EDB's) to disk.  See
the [first notebook](./01_estimation_mode.ipynb) for details.  The following module
will run a script to set everything up if the example data is not already available.

In [2]:
from est_mode_setup import prepare

prepare()

EDB directory already populated.

PosixPath('test-estimation-data/activitysim-prototype-mtc-extended')

# Load data and prep model for estimation

In [3]:
modelname="trip_destination"

In [4]:
from activitysim.estimation.larch import component_model
model, data = component_model(
    modelname,
    edb_directory=f"output-est-mode/estimation_data_bundle/{modelname}/",
    return_data=True,
)

loading from output-est-mode/estimation_data_bundle/trip_destination/trip_destination_coefficients.csv
loading from output-est-mode/estimation_data_bundle/trip_destination/trip_destination_SPEC.csv
loading from output-est-mode/estimation_data_bundle/trip_destination/trip_destination_alternatives_combined.parquet
loading from output-est-mode/estimation_data_bundle/trip_destination/trip_destination_choosers_combined.parquet
loading from output-est-mode/estimation_data_bundle/trip_destination/trip_destination_landuse.csv
loading from output-est-mode/estimation_data_bundle/trip_destination/trip_destination_size_terms.csv

/Users/jpn/Git/est-mode/activitysim/activitysim/estimation/larch/location_choice.py:548: UserWarning: Removed 5419 choosers with invalid (zero-sized) observed choice
  return location_choice_model(

# Review data loaded from EDB

Next we can review what was read the EDB, including the coefficients, model settings, utilities specification, and chooser and alternative data.

## coefficients

In [5]:
data.coefficients

                                       value constrain
coefficient_name
coef_UNAVAILABLE                 -999.000000         T
coef_one                            1.000000         T
coef_mode_choice_logsum             1.821000         F
coef_distance_joint                -0.123800         F
coef_util_distance_work_outbound   -0.049726         F
coef_util_distance_work_inbound     0.147813         F
coef_util_distance_univ            -0.061300         F
coef_util_distance_school          -0.105600         F
coef_util_distance_escort          -0.149100         F
coef_util_distance_shopping        -0.119200         F
coef_util_distance_eatout          -0.102900         F
coef_util_distance_othmaint        -0.096200         F
coef_util_distance_social          -0.132900         F
coef_util_distance_othdiscr        -0.126172         F
coef_util_distance_atwork          -0.122335         F
coef_prox_home_outbound_work       -0.380000         F
coef_prox_home_inbound_work        -0.150000         F
coef_prox_dest_outbound_work       -0.260000         F

## alt_values

In [6]:
data.alt_values

,trip_id,dest_taz,util_size_term,util_no_attractions,util_distance_inbound,util_distance_outbound,util_distance_joint,util_prox_home_outbound,util_prox_home_inbound,util_prox_dest_outbound,util_prox_dest_inbound,util_sample_of_alternatives_correction_factor,util_mode_choice_logsum_os,util_stop_not_accessible_by_this_tour_mode,util_mode_choice_logsum_sd,util_dest_not_accessible_by_this_tour_mode
0,439241,2,6.117394,False,0.000000,14.110000,0.0,6.89,0.000000,7.22,0.00,6.128602,-0.847005,False,-0.633253,False
1,439241,11,7.726934,False,0.000000,12.280001,0.0,5.90,0.000000,6.38,0.00,3.637608,-0.558405,False,-0.497479,False
2,439241,16,7.935721,False,0.000000,14.280000,0.0,6.81,0.000000,7.47,0.00,3.634621,-0.681632,False,-0.639591,False
3,439241,21,5.953480,False,0.000000,12.920000,0.0,6.13,0.000000,6.79,0.00,5.476918,-0.536647,False,-0.524008,False
4,439241,82,5.890218,False,0.000000,9.790000,0.0,4.83,0.000000,4.96,0.00,5.218103,-0.383122,False,-0.265333,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
854498,2481262477,1314,6.565007,False,21.299999,0.000000,0.0,0.00,10.650000,0.00,10.65,3.869640,-3.466365,False,-3.466365,False
854499,2481262477,1315,5.491167,False,14.500000,0.000000,0.0,0.00,7.250000,0.00,7.25,2.986897,-2.475631,False,-2.476182,False
854500,2481262477,1318,4.109496,False,35.799999,0.000000,0.0,0.00,17.900000,0.00,17.90,7.056036,-6.066198,False,-6.054759,False
854501,2481262477,1324,5.586113,False,40.349998,0.000000,0.0,0.00,19.950001,0.00,20.40,6.153502,-6.458255,False,-6.443607,False
854502,2481262477,1361,7.160701,False,60.360001,0.000000,0.0,0.00,30.180000,0.00,30.18,7.103621,-9.888594,False,-9.902823,False

## chooser_data

In [7]:
data.chooser_data

,trip_id,model_choice,override_choice,person_id,household_id,primary_purpose,trip_num,outbound,trip_count,destination,...,purpose,next_trip_id,tour_mode,trip_period,is_joint,tour_leg_dest,purpose_index_num,tour_mode_is_walk,tour_mode_is_bike,destination_logsum
0,439241,93,178,1339,1339,eatout,1,True,2,187,...,shopping,439242,DRIVEALONEFREE,PM,False,187.0,2,False,False,NaN
1,497189,169,99,1515,1515,shopping,1,False,2,170,...,othdiscr,497190,DRIVEALONEFREE,EV,False,170.0,6,False,False,NaN
2,536181,184,177,1634,1634,othmaint,1,False,2,178,...,othmaint,536182,DRIVEALONEFREE,PM,False,178.0,4,False,False,NaN
3,593909,183,136,1810,1810,othmaint,1,False,3,183,...,escort,593910,SHARED2FREE,AM,False,183.0,1,False,False,NaN
4,593910,89,188,1810,1810,othmaint,2,False,3,183,...,othmaint,593911,SHARED2FREE,AM,False,183.0,4,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36442,2480879045,1304,1306,7563655,2872320,othdiscr,1,False,2,1293,...,othdiscr,2480879046,DRIVEALONEFREE,MD,False,1293.0,6,False,False,NaN
36443,2480879069,1298,1299,7563655,2872320,othmaint,1,False,4,1293,...,shopping,2480879070,DRIVEALONEFREE,PM,False,1293.0,2,False,False,NaN
36444,2480879070,1291,1293,7563655,2872320,othmaint,2,False,4,1293,...,eatout,2480879071,DRIVEALONEFREE,PM,False,1293.0,3,False,False,NaN
36445,2480879071,1293,1293,7563655,2872320,othmaint,3,False,4,1293,...,othdiscr,2480879072,DRIVEALONEFREE,PM,False,1293.0,6,False,False,NaN
36446,2481262477,1309,1302,7564824,2873489,othdiscr,1,False,2,1310,...,shopping,2481262478,DRIVEALONEFREE,PM,False,1310.0,2,False,False,NaN

## landuse

In [8]:
data.landuse

,DISTRICT,SD,county_id,TOTHH,TOTPOP,TOTACRE,RESACRE,CIACRE,TOTEMP,AGE0519,...,area_type,HSENROLL,COLLFTE,COLLPTE,TOPOLOGY,TERMINAL,household_density,employment_density,density_index,is_cbd
zone_id,,,,,,,,,,,,,,,,,,,,,
1,1,1,1,46,82,20.3,1.0,15.00000,27318,7,...,0,0.0,0.00000,0.0,3,5.89564,2.875000,1707.375000,2.870167,False
2,1,1,1,134,240,31.1,1.0,24.79297,42078,19,...,0,0.0,0.00000,0.0,1,5.84871,5.195214,1631.374751,5.178722,False
3,1,1,1,267,476,14.7,1.0,2.31799,2445,38,...,0,0.0,0.00000,0.0,1,5.53231,80.470405,736.891913,72.547987,False
4,1,1,1,151,253,19.3,1.0,18.00000,22434,20,...,0,0.0,0.00000,0.0,2,5.64330,7.947368,1180.736842,7.894233,False
5,1,1,1,611,1069,52.7,1.0,15.00000,15662,86,...,0,0.0,72.14684,0.0,1,5.52555,38.187500,978.875000,36.753679,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,34,34,9,2724,6493,1320.0,630.0,69.00000,1046,1013,...,4,0.0,0.00000,0.0,1,1.12116,3.896996,1.496423,1.081235,False
1451,34,34,9,2016,4835,664.0,379.0,43.00000,757,757,...,4,0.0,0.00000,0.0,1,1.17116,4.777251,1.793839,1.304140,False
1452,34,34,9,2178,5055,1068.0,602.0,35.00000,2110,789,...,4,0.0,0.00000,0.0,1,1.17587,3.419152,3.312402,1.682465,False
1453,34,34,9,298,779,14195.0,429.0,4.00000,922,88,...,5,0.0,0.00000,0.0,1,1.01972,0.688222,2.129330,0.520115,False
1454,34,34,9,1068,2337,10469.0,1114.0,27.00000,607,418,...,5,0.0,0.00000,0.0,1,0.95542,0.936021,0.531989,0.339203,False

## spec

In [9]:
data.spec

,Label,Description,Expression,work,univ,school,escort,shopping,eatout,othmaint,social,othdiscr,atwork
0,util_size_term,size term,"@np.log1p(size_terms.get(df.dest_taz, df.purpo...",coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one
1,util_no_attractions,no attractions,"@size_terms.get(df.dest_taz, df.purpose) == 0 ...",coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE
2,util_distance_inbound,distance (calibration adjustment individual - ...,@(~df.is_joint & ~df.outbound) * (_od_DIST + _...,coef_util_distance_work_outbound,coef_util_distance_univ,coef_util_distance_school,coef_util_distance_escort,coef_util_distance_shopping,coef_util_distance_eatout,coef_util_distance_othmaint,coef_util_distance_social,coef_util_distance_othdiscr,coef_util_distance_atwork
3,util_distance_outbound,distance (calibration adjustment individual - ...,@(~df.is_joint & df.outbound) * (_od_DIST + _d...,coef_util_distance_work_inbound,coef_util_distance_univ,coef_util_distance_school,coef_util_distance_escort,coef_util_distance_shopping,coef_util_distance_eatout,coef_util_distance_othmaint,coef_util_distance_social,coef_util_distance_othdiscr,coef_util_distance_atwork
4,util_distance_joint,distance (calibration adjustment joint),@df.is_joint * (_od_DIST + _dp_DIST),NaN,NaN,NaN,coef_distance_joint,coef_distance_joint,coef_distance_joint,coef_distance_joint,coef_distance_joint,coef_distance_joint,NaN
5,util_prox_home_outbound,stop proximity to home (outbound),@df.outbound * _od_DIST,coef_prox_home_outbound_work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,util_prox_home_inbound,stop proximity to home (inbound),@~df.outbound * _dp_DIST,coef_prox_home_inbound_work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,util_prox_dest_outbound,stop proximity to main destination (outbound),@df.outbound * _dp_DIST,coef_prox_dest_outbound_work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,util_prox_dest_inbound,stop proximity to main destination (inbound),@~df.outbound * _od_DIST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,util_sample_of_alternatives_correction_factor,Sample of alternatives correction factor,"@np.minimum(np.log(df.pick_count/df.prob), 60)",coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one,coef_one
10,util_mode_choice_logsum_os,Mode choice logsum from origin to stop,od_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum
11,util_stop_not_accessible_by_this_tour_mode,Can't access stop zone by this tour mode,(od_logsum < -100),coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE
12,util_mode_choice_logsum_sd,Mode choice logsum from stop to destination,dp_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum,coef_mode_choice_logsum
13,util_dest_not_accessible_by_this_tour_mode,Can't access destination zone by this tour mode,(dp_logsum < -100),coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE,coef_UNAVAILABLE

## size_spec

In [10]:
data.size_spec

,TOTHH,RETEMPN,FPSEMPN,HEREMPN,OTHEMPN,AGREMPN,MWTEMPN,AGE0519,HSENROLL,COLLFTE,COLLPTE
segment,,,,,,,,,,,
work,0.000,1.000,1.0,1.000,1.000,1.0,1.0,0.000,0.000,0.000,0.000
escort,0.001,0.225,0.0,0.144,0.000,0.0,0.0,0.464,0.166,0.000,0.000
shopping,0.001,0.999,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000
eatout,0.000,0.742,0.0,0.258,0.000,0.0,0.0,0.000,0.000,0.000,0.000
othmaint,0.001,0.481,0.0,0.518,0.000,0.0,0.0,0.000,0.000,0.000,0.000
social,0.001,0.521,0.0,0.478,0.000,0.0,0.0,0.000,0.000,0.000,0.000
othdiscr,0.252,0.212,0.0,0.272,0.165,0.0,0.0,0.000,0.098,0.000,0.000
univ,0.001,0.000,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.592,0.408

# Estimate

With the model setup for estimation, the next step is to estimate the model coefficients.  Make sure to use a sufficiently large enough household sample and set of zones to avoid an over-specified model, which does not have a numerically stable likelihood maximizing solution.  Larch has a built-in estimation methods including BHHH, and also offers access to more advanced general purpose non-linear optimizers in the `scipy` package, including SLSQP, which allows for bounds and constraints on parameters.  BHHH is the default and typically runs faster, but does not follow constraints on parameters.

In [11]:
model.estimate(method='SLSQP', options={'maxiter':1000})

,value,best,initvalue,minimum,maximum,nullvalue,holdfast
param_name,,,,,,,
coef_UNAVAILABLE,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.0,1
coef_distance_joint,-0.222590,-0.222590,-0.123800,-25.000000,25.000000,0.0,0
coef_mode_choice_logsum,0.908189,0.908189,1.821000,-25.000000,25.000000,0.0,0
coef_one,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1
coef_prox_dest_outbound_work,-0.278949,-0.278949,-0.260000,-25.000000,25.000000,0.0,0
coef_prox_home_inbound_work,-0.121975,-0.121975,-0.150000,-25.000000,25.000000,0.0,0
coef_prox_home_outbound_work,-0.419012,-0.419012,-0.380000,-25.000000,25.000000,0.0,0
coef_util_distance_atwork,-0.122335,-0.122335,-0.122335,-25.000000,25.000000,0.0,0
coef_util_distance_eatout,-0.219723,-0.219723,-0.102900,-25.000000,25.000000,0.0,0
coef_util_distance_escort,-0.235858,-0.235858,-0.149100,-25.000000,25.000000,0.0,0
coef_util_distance_othdiscr,-0.241573,-0.241573,-0.126172,-25.000000,25.000000,0.0,0
coef_util_distance_othmaint,-0.177610,-0.177610,-0.096200,-25.000000,25.000000,0.0,0
coef_util_distance_school,-0.105600,-0.105600,-0.105600,-25.000000,25.000000,0.0,0
coef_util_distance_shopping,-0.227090,-0.227090,-0.119200,-25.000000,25.000000,0.0,0
coef_util_distance_social,-0.227558,-0.227558,-0.132900,-25.000000,25.000000,0.0,0
coef_util_distance_univ,-0.139388,-0.139388,-0.061300,-25.000000,25.000000,0.0,0
coef_util_distance_work_inbound,0.089849,0.089849,0.147813,-25.000000,25.000000,0.0,0
coef_util_distance_work_outbound,-0.138174,-0.138174,-0.049726,-25.000000,25.000000,0.0,0
eatout_HEREMPN,-2.550718,-2.550718,-1.354796,-6.000000,6.000000,0.0,0
eatout_RETEMPN,-0.298406,-0.298406,-0.298406,-0.298406,-0.298406,0.0,1
escort_AGE0519,-0.039579,-0.039579,-0.767871,-6.000000,6.000000,0.0,0
escort_HEREMPN,-2.848681,-2.848681,-1.937942,-6.000000,6.000000,0.0,0
escort_HSENROLL,-2.260284,-2.260284,-1.795768,-6.000000,6.000000,0.0,0
escort_RETEMPN,-0.886457,-0.886457,-1.491655,-6.000000,6.000000,0.0,0
escort_TOTHH,-6.907755,-6.907755,-6.907755,-6.907755,-6.907755,0.0,1
othdiscr_HEREMPN,-4.394168,-4.394168,-1.301953,-6.000000,6.000000,0.0,0
othdiscr_HSENROLL,-3.310820,-3.310820,-2.322788,-6.000000,6.000000,0.0,0
othdiscr_OTHEMPN,-2.825965,-2.825965,-1.801810,-6.000000,6.000000,0.0,0
othdiscr_RETEMPN,-2.884521,-2.884521,-1.551169,-6.000000,6.000000,0.0,0
othdiscr_TOTHH,-1.378326,-1.378326,-1.378326,-1.378326,-1.378326,0.0,1
othmaint_HEREMPN,-1.693356,-1.693356,-0.657780,-6.000000,6.000000,0.0,0
othmaint_RETEMPN,-0.351270,-0.351270,-0.731888,-6.000000,6.000000,0.0,0
othmaint_TOTHH,-6.907755,-6.907755,-6.907755,-6.907755,-6.907755,0.0,1
shopping_RETEMPN,-6.000000,-6.000000,-0.001001,-6.000000,6.000000,0.0,0
shopping_TOTHH,-6.907755,-6.907755,-6.907755,-6.907755,-6.907755,0.0,1
social_HEREMPN,-1.516222,-1.516222,-0.738145,-6.000000,6.000000,0.0,0
social_RETEMPN,-0.098839,-0.098839,-0.652005,-6.000000,6.000000,0.0,0
social_TOTHH,-6.907755,-6.907755,-6.907755,-6.907755,-6.907755,0.0,1
univ_COLLFTE,-6.000000,-6.000000,-0.524249,-6.000000,6.000000,0.0,0
univ_COLLPTE,-6.000000,-6.000000,-0.896488,-6.000000,6.000000,0.0,0
univ_TOTHH,-6.907755,-6.907755,-6.907755,-6.907755,-6.907755,0.0,1
work_AGREMPN,0.122431,0.122431,0.000000,-6.000000,6.000000,0.0,0
work_FPSEMPN,-6.000000,-6.000000,0.000000,-6.000000,6.000000,0.0,0
work_HEREMPN,-1.959508,-1.959508,0.000000,-6.000000,6.000000,0.0,0
work_MWTEMPN,-5.322959,-5.322959,0.000000,-6.000000,6.000000,0.0,0
work_OTHEMPN,-2.512682,-2.512682,0.000000,-6.000000,6.000000,0.0,0
work_RETEMPN,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1

/Users/jpn/Git/est-mode/larch/src/larch/model/jaxmodel.py:1156: PossibleOverspecification: Model is possibly over-specified (hessian is nearly singular).
  self.calculate_parameter_covariance()

┣                x: coef_UNAVAILABLE                   -999.000000
┃                   coef_distance_joint                  -0.222590
┃                   coef_mode_choice_logsum               0.908189
┃                   coef_one                              1.000000
┃                   coef_prox_dest_outbound_work         -0.278949
┃                   coef_prox_home_inbound_work          -0.121975
┃                   coef_prox_home_outbound_work         -0.419012
┃                   coef_util_distance_atwork            -0.122335
┃                   coef_util_distance_eatout            -0.219723
┃                   coef_util_distance_escort            -0.235858
┃                   coef_util_distance_othdiscr          -0.241573
┃                   coef_util_distance_othmaint          -0.177610
┃                   coef_util_distance_school            -0.105600
┃                   coef_util_distance_shopping          -0.227090
┃                   coef_util_distance_social            -0.227558
┃                   coef_util_distance_univ              -0.139388
┃                   coef_util_distance_work_inbound       0.089849
┃                   coef_util_distance_work_outbound     -0.138174
┃                   eatout_HEREMPN                       -2.550718
┃                   eatout_RETEMPN                       -0.298406
┃                   escort_AGE0519                       -0.039579
┃                   escort_HEREMPN                       -2.848681
┃                   escort_HSENROLL                      -2.260284
┃                   escort_RETEMPN                       -0.886457
┃                   escort_TOTHH                         -6.907755
┃                   othdiscr_HEREMPN                     -4.394168
┃                   othdiscr_HSENROLL                    -3.310820
┃                   othdiscr_OTHEMPN                     -2.825965
┃                   othdiscr_RETEMPN                     -2.884521
┃                   othdiscr_TOTHH                       -1.378326
┃                   othmaint_HEREMPN                     -1.693356
┃                   othmaint_RETEMPN                     -0.351270
┃                   othmaint_TOTHH                       -6.907755
┃                   shopping_RETEMPN                     -6.000000
┃                   shopping_TOTHH                       -6.907755
┃                   social_HEREMPN                       -1.516222
┃                   social_RETEMPN                       -0.098839
┃                   social_TOTHH                         -6.907755
┃                   univ_COLLFTE                         -6.000000
┃                   univ_COLLPTE                         -6.000000
┃                   univ_TOTHH                           -6.907755
┃                   work_AGREMPN                          0.122431
┃                   work_FPSEMPN                         -6.000000
┃                   work_HEREMPN                         -1.959508
┃                   work_MWTEMPN                         -5.322959
┃                   work_OTHEMPN                         -2.512682
┃                   work_RETEMPN                          0.000000
┃                   dtype: float64
┣          logloss: 2.543504818049292
┣        d_logloss: coef_UNAVAILABLE                    0.000000
┃                   coef_distance_joint                 0.000054
┃                   coef_mode_choice_logsum             0.000028
┃                   coef_one                            0.000000
┃                   coef_prox_dest_outbound_work       -0.000016
┃                   coef_prox_home_inbound_work         0.000044
┃                   coef_prox_home_outbound_work       -0.000010
┃                   coef_util_distance_atwork           0.000000
┃                   coef_util_distance_eatout           0.000017
┃                   coef_util_distance_escort           0.000004
┃                   coef_util_distance_othdiscr        -0.000030
┃                   coef_util_distance_othmaint        -0.000009
┃                   coef_util_distance_school           0.000000
┃                   coef_util_distance_shopping         0.000006
┃                   coef_util_distance_social          -0.000076
┃                   coef_util_distance_univ             0.000026
┃                   coef_util_distance_work_inbound    -0.000026
┃                   coef_util_distance_work_outbound    0.000069
┃                   eatout_HEREMPN                     -0.000049
┃                   eatout_RETEMPN                      0.000000
┃                   escort_AGE0519                     -0.000144
┃                   escort_HEREMPN                      0.000048
┃                   escort_HSENROLL                     0.000044
┃                   escort_RETEMPN                      0.000042
┃                   escort_TOTHH                        0.000000
┃                   othdiscr_HEREMPN                    0.000056
┃                   othdiscr_HSENROLL                  -0.000088
┃                   othdiscr_OTHEMPN                    0.000216
┃                   othdiscr_RETEMPN                   -0.000059
┃                   othdiscr_TOTHH                      0.000000
┃                   othmaint_HEREMPN                   -0.000220
┃                   othmaint_RETEMPN                   -0.000006
┃                   othmaint_TOTHH                      0.000000
┃                   shopping_RETEMPN                   -0.005801
┃                   shopping_TOTHH                      0.000000
┃                   social_HEREMPN                      0.000007
┃                   social_RETEMPN                     -0.000072
┃                   social_TOTHH                        0.000000
┃                   univ_COLLFTE                       -0.003131
┃                   univ_COLLPTE                       -0.002441
┃                   univ_TOTHH                          0.000000
┃                   work_AGREMPN                       -0.000051
┃                   work_FPSEMPN                       -0.000190
┃                   work_HEREMPN                        0.000081
┃                   work_MWTEMPN                       -0.000196
┃                   work_OTHEMPN                       -0.000045
┃                   work_RETEMPN                        0.000000
┃                   dtype: float64
┣              nit: 87
┣             nfev: 92
┣             njev: 87
┣           status: 0
┣          message: 'Optimization terminated successfully'
┣          success: True
┣     elapsed_time: datetime.timedelta(seconds=19, microseconds=360953)
┣           method: 'SLSQP'
┣          n_cases: 31028
┣ iteration_number: 87
┣          loglike: -78919.86749443343

### Estimated coefficients

In [12]:
model.parameter_summary()

# Output Estimation Results

In [13]:
from activitysim.estimation.larch import update_coefficients, update_size_spec
result_dir = data.edb_directory/"estimated"

## Write updated utility coefficients

In [14]:
update_coefficients(
    model, data, result_dir,
    output_file=f"{modelname}_coefficients_revised.csv",
);

## Write updated size coefficients

In [15]:
update_size_spec(
    model, data, result_dir, 
    output_file=f"{modelname}_size_terms.csv",
)

,segment,model_selector,TOTHH,RETEMPN,FPSEMPN,HEREMPN,OTHEMPN,AGREMPN,MWTEMPN,AGE0519,HSENROLL,COLLFTE,COLLPTE
0,work_low,workplace,0.000000,0.129129,0.193193,0.383383,0.120120,0.010010,0.164164,0.000000,0.000000,0.000000,0.000000
1,work_med,workplace,0.000000,0.120120,0.197197,0.325325,0.139139,0.008008,0.210210,0.000000,0.000000,0.000000,0.000000
2,work_high,workplace,0.000000,0.110000,0.207000,0.284000,0.154000,0.006000,0.239000,0.000000,0.000000,0.000000,0.000000
3,work_veryhigh,workplace,0.000000,0.093000,0.270000,0.241000,0.146000,0.004000,0.246000,0.000000,0.000000,0.000000,0.000000
4,university,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.592000,0.408000
5,gradeschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
6,highschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
7,escort,non_mandatory,0.000000,0.225000,0.000000,0.144000,0.000000,0.000000,0.000000,0.465000,0.166000,0.000000,0.000000
8,shopping,non_mandatory,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,eatout,non_mandatory,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,othmaint,non_mandatory,0.000000,0.482000,0.000000,0.518000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,social,non_mandatory,0.000000,0.522000,0.000000,0.478000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,othdiscr,non_mandatory,0.252252,0.212212,0.000000,0.272272,0.165165,0.000000,0.000000,0.000000,0.098098,0.000000,0.000000
13,atwork,atwork,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,work,trip,0.000000,0.423805,0.001051,0.059726,0.034350,0.479002,0.002067,0.000000,0.000000,0.000000,0.000000
15,escort,trip,0.000651,0.268207,0.000000,0.037695,0.000000,0.000000,0.000000,0.625554,0.067893,0.000000,0.000000
16,shopping,trip,0.287459,0.712541,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,eatout,trip,0.000000,0.904850,0.000000,0.095150,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,othmaint,trip,0.001125,0.791941,0.000000,0.206934,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,social,trip,0.000888,0.804213,0.000000,0.194899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,othdiscr,trip,0.605815,0.134341,0.000000,0.029688,0.142442,0.000000,0.000000,0.000000,0.087714,0.000000,0.000000
21,univ,trip,0.167856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.416072,0.416072

## Write the model estimation report, including coefficient t-statistic and log likelihood

In [16]:
model.to_xlsx(
    result_dir/f"{modelname}_model_estimation.xlsx", 
    data_statistics=False,
);

# Next Steps

The final step is to either manually or automatically copy the `*_coefficients_revised.csv` file and `*_size_terms.csv` file to the configs folder, rename them to `*_coefficients.csv` and `destination_choice_size_terms.csv`, and run ActivitySim in simulation mode.  Note that all the location
and desintation choice models share the same `destination_choice_size_terms.csv` input file, so if you
are updating all these models, you'll need to ensure that updated sections of this file for each model
are joined together correctly.

In [17]:
pd.read_csv(result_dir/f"{modelname}_coefficients_revised.csv")

                    coefficient_name       value constrain
0                   coef_UNAVAILABLE -999.000000         T
1                           coef_one    1.000000         T
2            coef_mode_choice_logsum    0.908189         F
3                coef_distance_joint   -0.222590         F
4   coef_util_distance_work_outbound   -0.138174         F
5    coef_util_distance_work_inbound    0.089849         F
6            coef_util_distance_univ   -0.139388         F
7          coef_util_distance_school   -0.105600         F
8          coef_util_distance_escort   -0.235858         F
9        coef_util_distance_shopping   -0.227090         F
10         coef_util_distance_eatout   -0.219723         F
11       coef_util_distance_othmaint   -0.177610         F
12         coef_util_distance_social   -0.227558         F
13       coef_util_distance_othdiscr   -0.241573         F
14         coef_util_distance_atwork   -0.122335         F
15      coef_prox_home_outbound_work   -0.419012         F
16       coef_prox_home_inbound_work   -0.121975         F
17      coef_prox_dest_outbound_work   -0.278949         F

In [18]:
pd.read_csv(result_dir/f"{modelname}_size_terms.csv")

,index,segment,model_selector,TOTHH,RETEMPN,FPSEMPN,HEREMPN,OTHEMPN,AGREMPN,MWTEMPN,AGE0519,HSENROLL,COLLFTE,COLLPTE
0,0,work_low,workplace,0.000000,0.129129,0.193193,0.383383,0.120120,0.010010,0.164164,0.000000,0.000000,0.000000,0.000000
1,1,work_med,workplace,0.000000,0.120120,0.197197,0.325325,0.139139,0.008008,0.210210,0.000000,0.000000,0.000000,0.000000
2,2,work_high,workplace,0.000000,0.110000,0.207000,0.284000,0.154000,0.006000,0.239000,0.000000,0.000000,0.000000,0.000000
3,3,work_veryhigh,workplace,0.000000,0.093000,0.270000,0.241000,0.146000,0.004000,0.246000,0.000000,0.000000,0.000000,0.000000
4,4,university,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.592000,0.408000
5,5,gradeschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
6,6,highschool,school,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
7,7,escort,non_mandatory,0.000000,0.225000,0.000000,0.144000,0.000000,0.000000,0.000000,0.465000,0.166000,0.000000,0.000000
8,8,shopping,non_mandatory,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,9,eatout,non_mandatory,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,10,othmaint,non_mandatory,0.000000,0.482000,0.000000,0.518000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,11,social,non_mandatory,0.000000,0.522000,0.000000,0.478000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,12,othdiscr,non_mandatory,0.252252,0.212212,0.000000,0.272272,0.165165,0.000000,0.000000,0.000000,0.098098,0.000000,0.000000
13,13,atwork,atwork,0.000000,0.742000,0.000000,0.258000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,14,work,trip,0.000000,0.423805,0.001051,0.059726,0.034350,0.479002,0.002067,0.000000,0.000000,0.000000,0.000000
15,15,escort,trip,0.000651,0.268207,0.000000,0.037695,0.000000,0.000000,0.000000,0.625554,0.067893,0.000000,0.000000
16,16,shopping,trip,0.287459,0.712541,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,17,eatout,trip,0.000000,0.904850,0.000000,0.095150,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,18,othmaint,trip,0.001125,0.791941,0.000000,0.206934,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,19,social,trip,0.000888,0.804213,0.000000,0.194899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,20,othdiscr,trip,0.605815,0.134341,0.000000,0.029688,0.142442,0.000000,0.000000,0.000000,0.087714,0.000000,0.000000
21,21,univ,trip,0.167856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.416072,0.416072